language:
  - cpp

compiler:
  - gcc

env:
  - BUILD_TYPE=Debug
  - BUILD_TYPE=Release
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "dG3gXqI65d45f7S6KrlqCgFun0id9Tw5tYOSud9lEYVvri6Qh6nJXEiqqVAsaZhZ7I/0cLMCQNmof3voFmOXpU+3NgQ3+t/vpe6PW65phR5O7hQl05YMApyP5ipq+KozLUL6ZAgX7eaU95rI/iPGYMfcZ2W3Jl7szGpxaZZOKrM="

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.9; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
  - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

#env:
  #- BUILD_TYPE=Debug
  #- BUILD_TYPE=Release

install:
  - cmake .
  - make

script:
  - cd test
  - ./test_bin



#before_install:
      #- echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  coverity_scan:
    project:
      name: "cs0rbagomba/graph"
      description: "Build submitted via Travis CI"
    notification_email: denes.matetelki@gmail.com
    #build_command_prepend: "./configure; make clean"
    build_command_prepend: "cmake ."
    build_command:   "make -j 4"
    branch_pattern: master