language: cpp

compiler:
  - gcc

before_install:
 - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
 - sudo apt-get -qq update
 - sudo apt-get -qq install g++-4.8

env:
  - BUILD_TYPE=Debug
  - BUILD_TYPE=Release

install:
  - cmake .
  - make

script:
  - cd test
  - test_bin